//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateIt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public long Id { get; set; }
        public long SubDirectoryId { get; set; }
        public long UserId { get; set; }
        public long CommentId { get; set; }
        public string ActivityText { get; set; }
        public System.DateTime Timestamp { get; set; }
        public long ActivityTypeId { get; set; }
        public long ContentId { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual SubDirectory SubDirectory { get; set; }
        public virtual User User { get; set; }
        public virtual ActivityType ActivityType { get; set; }
        public virtual Content Content { get; set; }
    }
}
