//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateIt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditTransaction
    {
        public int Id { get; set; }
        public long FromUserId { get; set; }
        public long ToUserId { get; set; }
        public double Amount { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string AdminNotes { get; set; }
        public string Notes { get; set; }
        public Nullable<long> LinkedId { get; set; }
        public long PaymentTypeId { get; set; }
    
        public virtual User User { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual User User1 { get; set; }
    }
}
