//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateIt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrowdfundingCampaign
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
        public string ImageLink { get; set; }
        public double TargetAmountMo { get; set; }
        public long ContentId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool Active { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual User User { get; set; }
    }
}
