//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateIt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investigation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Investigation()
        {
            this.ReportConfirms = new HashSet<ReportConfirm>();
        }
    
        public long Id { get; set; }
        public long CommentId { get; set; }
        public int OverallRemove { get; set; }
        public int OverallKeep { get; set; }
        public System.DateTime Timestamp { get; set; }
        public bool Resolved { get; set; }
        public int PassCounter { get; set; }
        public bool Removed { get; set; }
    
        public virtual Comment Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportConfirm> ReportConfirms { get; set; }
    }
}
