//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateIt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public long SubDirectoryId { get; set; }
        public long UserId { get; set; }
        public string NotificationText { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int NotificationTypeId { get; set; }
        public long ContentId { get; set; }
    
        public virtual Content Content { get; set; }
        public virtual NotificationType NotificationType { get; set; }
        public virtual SubDirectory SubDirectory { get; set; }
        public virtual User User { get; set; }
    }
}
