//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateIt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentChunk
    {
        public long Id { get; set; }
        public double TotalAllowenceInMo { get; set; }
        public double TotalValueOfEachParticipation { get; set; }
        public double TotalAllowenceInMoLeft { get; set; }
        public long CreditWalletId { get; set; }
        public System.DateTime IssuedAt { get; set; }
    
        public virtual CreditWallet CreditWallet { get; set; }
    }
}
