//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateIt.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoralityNetworkEntities : DbContext
    {
        public MoralityNetworkEntities()
            : base("name=MoralityNetworkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Activity> Activitys { get; set; }
        public virtual DbSet<ActivityType> ActivityTypes { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<ContentTransaction> ContentTransactions { get; set; }
        public virtual DbSet<ContentType> ContentTypes { get; set; }
        public virtual DbSet<CreditTransaction> CreditTransactions { get; set; }
        public virtual DbSet<CreditWallet> CreditWallets { get; set; }
        public virtual DbSet<CrowdfundingCampaign> CrowdfundingCampaigns { get; set; }
        public virtual DbSet<Currency> Currencys { get; set; }
        public virtual DbSet<GeneralNotification> GeneralNotifications { get; set; }
        public virtual DbSet<Investigation> Investigations { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NotificationType> NotificationTypes { get; set; }
        public virtual DbSet<PaymentChunk> PaymentChunks { get; set; }
        public virtual DbSet<PaymentTransfer> PaymentTransfers { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<PollAnswer> PollAnswers { get; set; }
        public virtual DbSet<Poll> Polls { get; set; }
        public virtual DbSet<PublisherChannel> PublisherChannels { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<ReportClaim> ReportClaims { get; set; }
        public virtual DbSet<ReportConfirm> ReportConfirms { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<SubDirectory> SubDirectorys { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<SystemNotification> SystemNotifications { get; set; }
        public virtual DbSet<SystemValue> SystemValues { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Upvote> Upvotes { get; set; }
        public virtual DbSet<UserConfirmation> UserConfirmations { get; set; }
        public virtual DbSet<UserContentValidation> UserContentValidations { get; set; }
        public virtual DbSet<UserMessage> UserMessages { get; set; }
        public virtual DbSet<UserPollingAnswer> UserPollingAnswers { get; set; }
        public virtual DbSet<UserRating> UserRatings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WithdrawTransfer> WithdrawTransfers { get; set; }
        public virtual DbSet<CountryCode> CountryCodes { get; set; }
        public virtual DbSet<Restriction> Restrictions { get; set; }
    }
}
