//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateIt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportConfirm
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public long InvestigationId { get; set; }
        public byte Remove { get; set; }
        public bool Toxic { get; set; }
        public bool Racism { get; set; }
        public bool Obscene { get; set; }
        public bool Threat { get; set; }
        public bool Insult { get; set; }
        public bool Hate { get; set; }
        public bool Spam { get; set; }
        public bool RemoveComment { get; set; }
        public bool IsDeactivated { get; set; }
    
        public virtual Investigation Investigation { get; set; }
        public virtual User User { get; set; }
    }
}
