//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateIt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restriction
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Reason { get; set; }
        public bool Active { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<int> CountryCodeId { get; set; }
    
        public virtual CountryCode CountryCode { get; set; }
    }
}
