//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateIt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemNotification
    {
        public long Id { get; set; }
        public string Message { get; set; }
        public string Code { get; set; }
        public System.DateTime Timestamp { get; set; }
        public bool Active { get; set; }
    }
}
