//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RateIt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemValue
    {
        public int Id { get; set; }
        public double AmountToPayForTraining { get; set; }
        public System.DateTime Timestamp { get; set; }
        public long AdminUserId { get; set; }
        public long AirdropMaxGiveAway { get; set; }
        public long AirdropDailyDistributeAmount { get; set; }
        public long AirdropThresholdBigPrizeGiveAway { get; set; }
        public long AirdropRandomDistribution { get; set; }
        public long AirdropMaxRandomAmount { get; set; }
        public int AirdropTotalUserCountMinThreshold { get; set; }
        public int AirdropMinThresholdUserPercent { get; set; }
        public int AirdropMaxThresholdUserPercent { get; set; }
        public int ValidationUserMaxCount { get; set; }
        public double ValidationUserThresholdPercent { get; set; }
        public int ValidationUserMaxRunCount { get; set; }
        public double AmountToPayForUserValidation { get; set; }
    
        public virtual User User { get; set; }
    }
}
